import pyautogui
import time
import os

while not os.path.isfile("C:\\Users\\User\\Desktop\\password.txt"):
    time.sleep(3)

password = ""
with open("C:\\Users\\User\\Desktop\\password.txt") as f:
    password = f.read()

time.sleep(3)
pyautogui.press('win')
time.sleep(1)
pyautogui.write('change your password', interval=0.05)
time.sleep(1)
pyautogui.press('enter')
time.sleep(5)
pyautogui.press('tab')
time.sleep(1)
pyautogui.press('tab')
time.sleep(1)
pyautogui.press('down')
time.sleep(1)
pyautogui.press('down')
time.sleep(1)
pyautogui.press('down')
time.sleep(1)
pyautogui.press('down')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
pyautogui.press('tab')
time.sleep(1)
pyautogui.press('tab')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
pyautogui.write(password, interval=0.05)
time.sleep(1)
pyautogui.press('tab')
time.sleep(1)
pyautogui.write(password, interval=0.05)
time.sleep(1)
pyautogui.press('tab')
time.sleep(1)
pyautogui.write('check msg', interval=0.05)
time.sleep(1)
pyautogui.press('tab')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
